export const MOCK_PRODUCTS = [
  // ═══════════════════════════════════════════════════════════════════
  // TIER ₪1,000 - BEST SELLER
  // ═══════════════════════════════════════════════════════════════════
  {
    id: "p1",
    title: "טאבון גז 500 מעלות עם אבן שמוט",
    description: "טאבון גז מקצועי עם אבן שמוט עמידה בחום – מגיע ל-500° תוך דקות.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 1000,
    consumer_price: 2490,
    warranty: "שנה אחריות",
    image: "https://media.base44.com/images/public/69f8ef4e14a99d2803ea13b4/09703ca65_generated_image.png",
    stock: 15,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: true,
  },
  {
    id: "p2",
    title: "גריל גז 3 מבערים עם כירת צד",
    description: "גריל גז מנירוסטה 3 מבערים, 7.5kW, מגש טפטוף נשלף + כירת צד.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 1000,
    consumer_price: 1690,
    warranty: "שנתיים אחריות",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80",
    stock: 12,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: true,
  },
  {
    id: "p3",
    title: "מקרר נייד לרכב 50 ליטר",
    description: "מקרר נייד 50 ליטר לרכב, קמפינג וסירות. שקט וקומפקטי.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 1000,
    consumer_price: 1990,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&q=80",
    stock: 10,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: true,
  },
  {
    id: "p4",
    title: "לילה זוגי מלון קדם",
    description: "לינה זוגית במלון קדם 5 כוכבים, כולל ארוחת בוקר עשירה.",
    category: "נסיעות",
    rewardType: "vacation",
    price_tier: 1000,
    consumer_price: 1000,
    warranty: "בתוקף שנה",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80",
    stock: 50,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // TIER ₪1,000 - בית וגינה
  // ═══════════════════════════════════════════════════════════════════
  {
    id: "p5",
    title: "טוחן אשפה 1 כ״ס",
    description: "טוחן אשפה מקצועי בכוח 1 כ״ס, עם הגנה אנטי-הצפה ותפעול שקט.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 1000,
    consumer_price: 1790,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&q=80",
    stock: 8,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p6",
    title: "מקרר ויטרינה 90 ליטר",
    description: "מקרר ויטרינה 90 ליטר עם דלת זכוכית ותאורת LED.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 1000,
    consumer_price: 1649,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&q=80",
    stock: 7,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p7",
    title: "מכשיר שטיפה בלחץ 2000W",
    description: "מכשיר שטיפה בלחץ 2000W, 150 בר, צינור 8 מטר.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 1000,
    consumer_price: 1590,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&q=80",
    stock: 11,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p8",
    title: "שמיכת חורף + מצעים יוקרתיים",
    description: "שמיכת פוך איכותית + סט מצעים מיקרופייבר 100%. חבילת פינוק.",
    category: "בית",
    rewardType: "home",
    price_tier: 1000,
    consumer_price: 1898,
    warranty: "ערבות שביעות רצון",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",
    stock: 30,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // TIER ₪1,000 - אלקטרוניקה
  // ═══════════════════════════════════════════════════════════════════
  {
    id: "p9",
    title: "מכונת קרח",
    description: "מכונת קרח ביתית מקצועית – מייצרת עד 12 ק״ג ליום.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 1000,
    consumer_price: 1790,
    warranty: "שנה אחריות",
    image: "https://media.base44.com/images/public/69f8ef4e14a99d2803ea13b4/7c6055f2b_generated_image.png",
    stock: 8,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p10",
    title: "כיסא גיימינג מקצועי",
    description: "כיסא גיימינג ארגונומי עם תמיכה לגב גבוהה וסוגורי זרוע.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 1000,
    consumer_price: 1290,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1631337282514-da82e50fbf97?w=600&q=80",
    stock: 10,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p11",
    title: "אוזניות Sony WH-1000XM5",
    description: "אוזניות Over-Ear פרמיום עם ביטול רעשים, 30 שעות סוללה.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 1000,
    consumer_price: 1290,
    warranty: "שנה אחריות יבואן",
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&q=80",
    stock: 20,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p12",
    title: "מגהץ קיטור Braun",
    description: "מגהץ קיטור Braun עם חימום מהיר וטנק גדול.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 1000,
    consumer_price: 1290,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1584622181563-430f63602d4b?w=600&q=80",
    stock: 12,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p13",
    title: "מכונת גלידה",
    description: "מכונת גלידה ביתית 2 ליטר, תוצאה בדקות ספורות.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 1000,
    consumer_price: 1290,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&q=80",
    stock: 9,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p14",
    title: "אוזניות Sony WF-1000XM6",
    description: "אוזניות In-Ear אלחוטיות, ביטול רעשים מתקדם.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 1000,
    consumer_price: 1190,
    warranty: "שנה אחריות יבואן",
    image: "https://images.unsplash.com/photo-1606220838315-056192d5e927?w=600&q=80",
    stock: 18,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p15",
    title: "טוסטר גריל Braun",
    description: "טוסטר אובן 2000W של Braun, 6 רמות חימום.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 1000,
    consumer_price: 990,
    warranty: "שנה אחריות יבואן",
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&q=80",
    stock: 25,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p16",
    title: "טאבלט Teclast + עט",
    description: "טאבלט 10.4 אינץ', 8GB RAM, 256GB, כולל עט חכם.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 1000,
    consumer_price: 1049,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80",
    stock: 14,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // TIER ₪1,000 - נסיעות ופנאי
  // ═══════════════════════════════════════════════════════════════════
  {
    id: "p17",
    title: "לילה זוגי מלון דיוויד ים המלח",
    description: "לינה ספא זוגית בים המלח, כולל כניסה לבריכת מינרלים.",
    category: "נסיעות",
    rewardType: "vacation",
    price_tier: 1000,
    consumer_price: 1000,
    warranty: "בתוקף שנה",
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80",
    stock: 50,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p18",
    title: "סט מזוודות + כרית צוואר",
    description: "סט מזוודות 3 חלקים + כרית צוואר נוחה לטיסות.",
    category: "פנאי",
    rewardType: "vacation",
    price_tier: 1000,
    consumer_price: 2700,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1469283057990-b0be3b8d9e5d?w=600&q=80",
    stock: 15,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // TIER ₪2,500 - BEST SELLER
  // ═══════════════════════════════════════════════════════════════════
  {
    id: "p19",
    title: "טלוויזיה Samsung 70 אינץ",
    description: "טלוויזיה QLED 4K 70 אינץ' עם Tizen Smart TV, HDR10+.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 2500,
    consumer_price: 3199,
    warranty: "שנה אחריות",
    image: "https://media.base44.com/images/public/69f8ef4e14a99d2803ea13b4/ff6758d7e_generated_image.png",
    stock: 10,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: true,
  },
  {
    id: "p20",
    title: "מערכת רמקולים + פטיפון",
    description: "פטיפון וינטאג' + זוג רמקולים פסיביים 50W. צליל עשיר.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 2500,
    consumer_price: 4580,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&q=80",
    stock: 6,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: true,
  },
  {
    id: "p21",
    title: "גריל גז 6 מבערים + טוחן אשפה",
    description: "גריל גז 6 מבערים 14kW נירוסטה פרמיום + טוחן אשפה.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 2500,
    consumer_price: 5280,
    warranty: "שנתיים אחריות",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80",
    stock: 5,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: true,
  },
  {
    id: "p22",
    title: "שואב שוטף + מכונת ברד/גלידה",
    description: "שואב רובוט חכם עם ניווט לייזר + מכונת גלידה 2 ליטר.",
    category: "בית",
    rewardType: "home",
    price_tier: 2500,
    consumer_price: 3490,
    warranty: "שנה אחריות",
    image: "https://media.base44.com/images/public/69f8ef4e14a99d2803ea13b4/37f84bb72_generated_image.png",
    stock: 8,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: true,
  },
  {
    id: "p23",
    title: "2 לילות מלון קדם",
    description: "שני לילות זוגיים במלון קדם 5 כוכבים, ארוחות בוקר.",
    category: "נסיעות",
    rewardType: "vacation",
    price_tier: 2500,
    consumer_price: 2500,
    warranty: "בתוקף שנה",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80",
    stock: 50,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // TIER ₪2,500 - אלקטרוניקה
  // ═══════════════════════════════════════════════════════════════════
  {
    id: "p24",
    title: "מערכת הגברה מקצועית 600W",
    description: "מערכת הגברה 600W עם רמקול סאב-וופר + 2 לוויינים.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 2500,
    consumer_price: 4590,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80",
    stock: 7,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p25",
    title: "מכונת קפה Delonghi",
    description: "DeLonghi Magnifica Evo – מכונת אספרסו פולים מלאה.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 2500,
    consumer_price: 2690,
    warranty: "שנה אחריות יבואן",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
    stock: 11,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p26",
    title: "מקרן קול SONY",
    description: "Soundbar Sony 300W, Bluetooth, Dolby Atmos.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 2500,
    consumer_price: 2990,
    warranty: "שנה אחריות Sony",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&q=80",
    stock: 9,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p27",
    title: "מחשב נייד Dell + ציוד",
    description: "Dell Inspiron 15, Core i5, 16GB, 512GB SSD + ציוד.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 2500,
    consumer_price: 2638,
    warranty: "שנה אחריות Dell",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80",
    stock: 5,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p28",
    title: "מיקסר BOBOT",
    description: "מיקסר עמידה מקצועי 1200W, 6.5 ליטר, 10 מהירויות.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 2500,
    consumer_price: 3000,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1621905767938-48416c8eddf1?w=600&q=80",
    stock: 13,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // TIER ₪2,500 - בית ופנאי
  // ═══════════════════════════════════════════════════════════════════
  {
    id: "p29",
    title: "שואב שוטף BOBOT",
    description: "רובוט שואב ושוטף חכם עם ניווט לייזר LiDAR.",
    category: "בית",
    rewardType: "home",
    price_tier: 2500,
    consumer_price: 2859,
    warranty: "שנה אחריות",
    image: "https://media.base44.com/images/public/69f8ef4e14a99d2803ea13b4/402fd60f5_generated_image.png",
    stock: 8,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p30",
    title: "מקרר זכוכית שחור",
    description: "מקרר ויטרינה 120 ליטר זכוכית שחורה עם LED.",
    category: "בית",
    rewardType: "home",
    price_tier: 2500,
    consumer_price: 2990,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=600&q=80",
    stock: 6,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p31",
    title: "רובוט ניקוי חלונות",
    description: "רובוט חלונות חכם עם מדחף ואקום, ניקוי אוטומטי.",
    category: "בית",
    rewardType: "home",
    price_tier: 2500,
    consumer_price: 2500,
    warranty: "שנה אחריות",
    image: "https://media.base44.com/images/public/69f8ef4e14a99d2803ea13b4/7e3a2e563_generated_image.png",
    stock: 6,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p32",
    title: "שמיכת פוך + מצעים יוקרתיים",
    description: "שמיכת פוך 100% + סט מצעים Bamboo Satin 600TC.",
    category: "בית",
    rewardType: "home",
    price_tier: 2500,
    consumer_price: 4198,
    warranty: "ערבות שביעות רצון",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",
    stock: 20,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p33",
    title: "שולחן כדורגל חוץ",
    description: "שולחן כדורגל עץ מלא עם מוטות מתכת.",
    category: "פנאי",
    rewardType: "home",
    price_tier: 2500,
    consumer_price: 2749,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    stock: 4,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // TIER ₪2,500 - נסיעות וטיפוח
  // ═══════════════════════════════════════════════════════════════════
  {
    id: "p34",
    title: "3 לילות הרודס הרצליה",
    description: "שלושה לילות ספא זוגיים במלון הרודס הרצליה.",
    category: "נסיעות",
    rewardType: "vacation",
    price_tier: 2500,
    consumer_price: 2500,
    warranty: "בתוקף שנה",
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80",
    stock: 30,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p35",
    title: "מכשיר IPL להסרת שיער + מכונת גילוח + גיפטקארד",
    description: "חבילת פינוק: מכשיר IPL + מכונת גילוח אלחוטית + גיפט.",
    category: "טיפוח",
    rewardType: "experience",
    price_tier: 2500,
    consumer_price: 2948,
    warranty: "בתוקף שנה",
    image: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=600&q=80",
    stock: 25,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
];

export const MOCK_CAMPAIGN = {
  id: "c1",
  name: "Q4 2024 - יעדי מכירות",
  employee_count: 85,
  success_rate: 78,
  price_tier: 1000,
  status: "active",
  sent_count: 85,
  opened_count: 71,
  selected_count: 52,
  budget_expected: 85000,
  budget_actual: 52000,
  deadline_days: 14
};

export const MOCK_ORDERS = [
  { id: "o1", employee_name: "רון לוי", employee_email: "ron@company.co.il", product_title: "אוזניות Sony WH-1000XM5", price_tier: 1000, consumer_price: 1290, status: "delivered", selected_at: "2024-01-10T09:00:00Z" },
  { id: "o2", employee_name: "שירה כהן", employee_email: "shira@company.co.il", product_title: "לילה לזוג – מלון קדם", price_tier: 1000, consumer_price: 1000, status: "shipped", selected_at: "2024-01-11T14:00:00Z" },
  { id: "o3", employee_name: "אמיר דוד", employee_email: "amir@company.co.il", product_title: "טלוויזיה Samsung 70 אינץ'", price_tier: 2500, consumer_price: 3199, status: "ordered", selected_at: "2024-01-12T10:00:00Z" },
  { id: "o4", employee_name: "מיכל גרין", employee_email: "michal@company.co.il", product_title: "גריל גז 3 מבערים עם כירת צד", price_tier: 1000, consumer_price: 1690, status: "pending", selected_at: "2024-01-13T16:00:00Z" },
  { id: "o5", employee_name: "יוסי אברהם", employee_email: "yossi@company.co.il", product_title: "טאבון גז 500 מעלות עם אבן שמוט", price_tier: 1000, consumer_price: 2490, status: "delivered", selected_at: "2024-01-09T08:00:00Z" },
];

export const STATUS_LABELS = {
  pending: "ממתין",
  selected: "נבחר",
  ordered: "הוזמן",
  shipped: "בדרך",
  delivered: "נמסר",
};

export const STATUS_COLORS = {
  pending: "bg-amber-100 text-amber-700",
  selected: "bg-blue-100 text-blue-700",
  ordered: "bg-indigo-100 text-indigo-700",
  shipped: "bg-purple-100 text-purple-700",
  delivered: "bg-green-100 text-green-700",
};