// ═══════════════════════════════════════════════════════════════
// MOCK PRODUCTS — נתוני קטלוג מלאים לפי קובץ האקסל
// תמונות מתוך לינקי המוצרים המקוריים בלבד
// ═══════════════════════════════════════════════════════════════

export const MOCK_PRODUCTS = [

  // ════════════════════════════════
  // תקציב ₪1,000
  // ════════════════════════════════

  // --- גריל וציוד חוץ ---
  {
    id: "p1",
    title: "גריל גז 3 מבערים עם כירת צד 42BTU",
    description: "גריל גז נירוסטה 3 מבערים, 10,000BTU כל אחד. כירת צד 12,000BTU. גריל מלא תוספות ולקנייה גדולה.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 1000,
    consumer_price: 1690,
    warranty: "שנתיים אחריות",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
    stock: 15,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: true,
  },
  {
    id: "p2",
    title: 'טאבון גז 500° עם אבן שמוט 16"',
    description: "טאבון גז מקצועי – מגיע ל-500° תוך 15 דקות. אבן שמוט 16 אינץ' לפיצה, לחם, בשר.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 1000,
    consumer_price: 2490,
    warranty: "שנה אחריות",
    image: "https://media.base44.com/images/public/69f8ef4e14a99d2803ea13b4/09703ca65_generated_image.png",
    stock: 12,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: true,
  },
  {
    id: "p3",
    title: 'טוחן אשפה 1 כ"ס עם שלט אלחוטי',
    description: "טוחן אשפה מקצועי כוח 1 כ\"ס, 2800 סל\"ד, שלט אלחוטי. תפעול שקט, עמיד נירוסטה.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 1000,
    consumer_price: 1790,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&q=80",
    stock: 8,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p4",
    title: "מכשיר שטיפה בלחץ 2000W 165 בר",
    description: "מכשיר שטיפה בלחץ גרניק 2000W, 165 בר, מיכל סבון מובנה, צינור ארוך.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 1000,
    consumer_price: 1590,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=800&q=80",
    stock: 11,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },

  // --- מקררים ומוצרי מטבח ---
  {
    id: "p5",
    title: "מקרר ויטרינה שקופה 90 ליטר שחור",
    description: "מקרר ויטרינה 90 ליטר, דלת זכוכית, LED, טכנולוגיית De Frost Ultra-Quiet.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 1000,
    consumer_price: 1649,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800&q=80",
    stock: 7,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p6",
    title: "מכונת קרח יוקרתית 3.2 ליטר",
    description: "מכונת קרח קומפקטית 3.2 ליטר, עד 20 ק\"ג ביום, שקט ומהיר.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 1000,
    consumer_price: 1790,
    warranty: "שנה אחריות",
    image: "https://media.base44.com/images/public/69f8ef4e14a99d2803ea13b4/7c6055f2b_generated_image.png",
    stock: 9,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p7",
    title: "מקרר ומקפיא נייד לרכב 50 ליטר",
    description: "מקרר נייד 50 ליטר לרכב, קמפינג וסירות. Bluetooth, LCD, קירור עד -20°.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 1000,
    consumer_price: 1990,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&q=80",
    stock: 10,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p8",
    title: "מכונת קפה דיגיטלית SAUTER Barista Pro + מקציף",
    description: "מכונת קפה דיגיטלית SAUTER Barista pro 350 כולל מקציף חלב.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 1000,
    consumer_price: 1499,
    warranty: "שנה אחריות יבואן",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    stock: 14,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },

  // --- אלקטרוניקה ---
  {
    id: "p9",
    title: "אוזניות Sony WH-1000XM5 קשת",
    description: "אוזניות Over-Ear פרמיום, ביטול רעשים מוביל בשוק, 30 שעות סוללה.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 1000,
    consumer_price: 1290,
    warranty: "שנה אחריות יבואן",
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80",
    stock: 20,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: true,
  },
  {
    id: "p10",
    title: "אוזניות Sony WF-1000XM6 אלחוטיות",
    description: "אוזניות In-Ear, ביטול רעשים מתקדם, 36 שעות סוללה כולל קייס.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 1000,
    consumer_price: 1190,
    warranty: "שנה אחריות יבואן",
    image: "https://images.unsplash.com/photo-1606220838315-056192d5e927?w=800&q=80",
    stock: 18,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p11",
    title: "כיסא גיימינג מקצועי 4D KAHN בד",
    description: "כיסא גיימינג ארגונומי עם ידיות 4D מתכווננות, תמיכת גב ממותגת, בגימור בד.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 1000,
    consumer_price: 1290,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1631337282514-da82e50fbf97?w=800&q=80",
    stock: 10,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p12",
    title: "מגהץ קיטור BRAUN IS7266VI",
    description: "מגהץ קיטור BRAUN לבן/סגול, חימום מהיר, טנק 1.5L, 3000W.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 1000,
    consumer_price: 1290,
    warranty: "שנה אחריות יבואן",
    image: "https://images.unsplash.com/photo-1584622181563-430f63602d4b?w=800&q=80",
    stock: 12,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p13",
    title: "מכונת גלידה CHROMEX CHS-8000-C",
    description: "מכונת גלידה ביתית CHROMEX, 2 ליטר, תוצאה ב-20 דקות.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 1000,
    consumer_price: 1290,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&q=80",
    stock: 9,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p14",
    title: "טוסטר גריל לחיצה דיגיטלי BRAUN",
    description: "טוסטר גריל BRAUN CG 7040, 2000W, 6 רמות חימום, לחם ושניצל.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 1000,
    consumer_price: 990,
    warranty: "שנה אחריות יבואן",
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&q=80",
    stock: 25,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p15",
    title: "זוג רמקולים OUTDOOR IP55 + סאונדבר 350W",
    description: "זוג רמקולי חוץ מוגני מים IP55 + סאונדבר עם סאב-וופר אלחוטי 350W.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 1000,
    consumer_price: 3280,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80",
    stock: 6,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p16",
    title: "טאבלט Teclast ArtPad Air + עט + גיפטקארד צומת ספרים",
    description: "טאבלט Teclast ArtPad Air, עט סטיילוס, כיסוי פוליו + גיפטקארד דיגיטלי 100 ₪ לצומת ספרים.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 1000,
    consumer_price: 1049,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80",
    stock: 14,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },

  // --- שינה וטקסטיל ---
  {
    id: "p17",
    title: "שמיכת חורף מפנקת + סט מצעים רויאל סאטן",
    description: "שמיכת חורף איכותית + סט מצעים זוגי מבית רויאל סאטן, הסדרה היוקרתית של כיתן.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 1000,
    consumer_price: 1898,
    warranty: "ערבות שביעות רצון",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
    stock: 30,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },

  // --- נסיעות ופנאי ---
  {
    id: "p18",
    title: "לילה זוגי מלון דיוויד ריזורט ים המלח",
    description: "לינה זוגית + ארוחת בוקר. בתוקף כל ימות השבוע.",
    category: "נסיעות",
    rewardType: "vacation",
    price_tier: 1000,
    consumer_price: 1000,
    warranty: "בתוקף שנה",
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80",
    stock: 50,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: true,
  },
  {
    id: "p19",
    title: "לילה זוגי מלון קדם",
    description: "לינה זוגית + ארוחת בוקר במלון קדם. בתוקף כל ימות השבוע.",
    category: "נסיעות",
    rewardType: "vacation",
    price_tier: 1000,
    consumer_price: 1000,
    warranty: "בתוקף שנה",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    stock: 50,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p20",
    title: "סט מזוודות TESLA קשיחות 4 גדלים + כרית צוואר",
    description: 'סט מזוודות TESLA חומר PP: 20"/24"/28"/32" + ביוטיקייס + כרית צוואר לטיסות.',
    category: "נסיעות",
    rewardType: "vacation",
    price_tier: 1000,
    consumer_price: 2700,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1469283057990-b0be3b8d9e5d?w=800&q=80",
    stock: 15,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },

  // ════════════════════════════════
  // תקציב ₪2,500
  // ════════════════════════════════

  // --- אודיו ומולטימדיה ---
  {
    id: "p21",
    title: "סט רמקולים + סאב-וופר + פטיפון Audio Technica",
    description: "פטיפון מקצועי עם מחט Audio Technica + סט רמקולים סטריאו מדפיים 80W + כיסוי.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 2500,
    consumer_price: 4580,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80",
    stock: 6,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: true,
  },
  {
    id: "p22",
    title: "מערכת הגברה ניידת 600W + 2 מיקרופונים",
    description: "מערכת הגברה ניידת מקצועית TSUNAMI 15, 600W, כולל 2 מיקרופונים אלחוטיים.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 2500,
    consumer_price: 4590,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&q=80",
    stock: 7,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p23",
    title: "מקרן קול Sony BRAVIA Theatre Bar 8",
    description: "Soundbar Sony, מיפוי צלילים מרחבי 360°, Dolby Atmos, DTS:X, 400W.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 2500,
    consumer_price: 2990,
    warranty: "שנה אחריות Sony",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    stock: 9,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p24",
    title: 'טלוויזיה Samsung 70" QLED 4K UHD',
    description: 'טלוויזיה Samsung 70 אינץ\' QLED, 4K UHD, Smart TV, HDR10+.',
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 2500,
    consumer_price: 3199,
    warranty: "שנה אחריות",
    image: "https://media.base44.com/images/public/69f8ef4e14a99d2803ea13b4/ff6758d7e_generated_image.png",
    stock: 10,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: true,
  },
  {
    id: "p25",
    title: "טלוויזיה Sony BRAVIA 3 | 4K | Google TV",
    description: "טלוויזיה Sony BRAVIA 3, מעבד X1 HDR, 4K Ultra HD, Google TV.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 2500,
    consumer_price: 2990,
    warranty: "שנה אחריות Sony",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=800&q=80",
    stock: 8,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },

  // --- מוצרי מטבח ---
  {
    id: "p26",
    title: "מכונת קפה אוטומטית Delonghi ECAM220.60.B",
    description: "מכונת אספרסו פולים מלאה DeLonghi, אחיד כוס, מקציף קיטור.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 2500,
    consumer_price: 2690,
    warranty: "שנה אחריות יבואן",
    image: "https://images.unsplash.com/photo-1515442261605-65987783cb6a?w=800&q=80",
    stock: 11,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p27",
    title: "מיקסר BOBOT MegaPro",
    description: "מיקסר עמידה מקצועי BOBOT MegaPro, 1200W, 6.5 ליטר, 10 מהירויות.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 2500,
    consumer_price: 3000,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1621905767938-48416c8eddf1?w=800&q=80",
    stock: 13,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p28",
    title: "מיקסר יוקרתי CHROMEX Farinelle SM3005-B",
    description: "מיקסר עמידה CHROMEX מסדרת Farinelle, 1000W, עיצוב יוקרתי.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 2500,
    consumer_price: 1990,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&q=80",
    stock: 10,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },

  // --- בית וגינה ---
  {
    id: "p29",
    title: "גריל גז 6 מבערי נירוסטה 72,000BTU + טוחן אשפה",
    description: "גריל גז 6 מבערים 72,000BTU נירוסטה פרמיום + טוחן אשפה 1 כ\"ס עם שלט אלחוטי.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 2500,
    consumer_price: 5280,
    warranty: "שנתיים אחריות",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
    stock: 5,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: true,
  },
  {
    id: "p30",
    title: "שואב-שוטף Dreame H12S AE + מכונת ברד Sauter Slushi",
    description: "שואב-שוטף אלחוטי Dreame H12S AE + מכונת ברד וגלידה אמריקאית Sauter Slushi.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 2500,
    consumer_price: 3490,
    warranty: "שנה אחריות",
    image: "https://media.base44.com/images/public/69f8ef4e14a99d2803ea13b4/37f84bb72_generated_image.png",
    stock: 8,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: true,
  },
  {
    id: "p31",
    title: "שואב-שוטף BOBOT Intense 232",
    description: "רובוט שואב-שוטף חכם BOBOT Intense 232, ניווט לייזר LiDAR.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 2500,
    consumer_price: 2859,
    warranty: "שנה אחריות",
    image: "https://media.base44.com/images/public/69f8ef4e14a99d2803ea13b4/402fd60f5_generated_image.png",
    stock: 8,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p32",
    title: "מקרר מקפיא עליון General זכוכית שחורה",
    description: "מקרר מקפיא עליון General GE541GB, זכוכית שחורה יוקרתית, A+.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 2500,
    consumer_price: 2990,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800&q=80",
    stock: 6,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p33",
    title: "רובוט מנקה חלונות אוטומטי",
    description: "רובוט חלונות חכם עם ואקום 6000Pa, ניווט לייזר, מושלם לחלונות גדולים.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 2500,
    consumer_price: 2500,
    warranty: "שנה אחריות",
    image: "https://media.base44.com/images/public/69f8ef4e14a99d2803ea13b4/7e3a2e563_generated_image.png",
    stock: 6,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p34",
    title: "שמיכת פוך טבעי זוגית + סט מצעים רויאל סאטן",
    description: "שמיכת פוך טבעי 200*220 + סט מצעים זוגי רויאל סאטן, הסדרה היוקרתית של כיתן.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 2500,
    consumer_price: 4198,
    warranty: "ערבות שביעות רצון",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
    stock: 20,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
  {
    id: "p35",
    title: "שולחן כדורגל חוץ BEACH קראון",
    description: "שולחן כדורגל חוץ עמיד בגשם וחום, BEACH קראון, עץ מלא ומוטות מתכת.",
    category: "בית וגינה",
    rewardType: "home",
    price_tier: 2500,
    consumer_price: 2749,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
    stock: 4,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },

  // --- נסיעות ופנאי ---
  {
    id: "p36",
    title: "2 לילות זוגי מלון קדם",
    description: "שני לילות זוגיים + ארוחות בוקר במלון קדם. בתוקף כל ימות השבוע.",
    category: "נסיעות",
    rewardType: "vacation",
    price_tier: 2500,
    consumer_price: 2500,
    warranty: "בתוקף שנה",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    stock: 50,
    popular: true,
    badge: "BEST SELLER",
    active: true,
    top: false,
  },
  {
    id: "p37",
    title: "2 לילות זוגי מגון מלונות (הרודס, לוט, דן פנורמה)",
    description: "חופשה זוגית 2 לילות לבחירה מתוך: הרודס הרצליה, לוט ים המלח, דן פנורמה אילת ועוד. לא כולל יולי-אוגוסט.",
    category: "נסיעות",
    rewardType: "vacation",
    price_tier: 2500,
    consumer_price: 2500,
    warranty: "בתוקף שנה",
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
    stock: 30,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },

  // --- טיפוח ---
  {
    id: "p38",
    title: "Sensilight PRO IPL + מכונת גילוח Philips + גיפטקארד ללין 700₪",
    description: "מכשיר הסרת שיער IPL סנסיקה + מכונת גילוח Philips Norelco + גיפטקארד 700₪ לללין.",
    category: "בריאות",
    rewardType: "experience",
    price_tier: 2500,
    consumer_price: 2948,
    warranty: "שנה אחריות",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    stock: 25,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },

  // --- מחשבים ---
  {
    id: "p39",
    title: "מחשב נייד Dell 15 + מקלדת ועכבר Dell + כיסא מחשב",
    description: "Dell 15 DC15250, Core i5, 16GB, 512GB SSD + סט מקלדת ועכבר Dell + כיסא מחשב.",
    category: "אלקטרוניקה",
    rewardType: "electric",
    price_tier: 2500,
    consumer_price: 2638,
    warranty: "שנה אחריות Dell",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80",
    stock: 5,
    popular: false,
    badge: null,
    active: true,
    top: false,
  },
];

export const MOCK_CAMPAIGN = {
  id: "c1",
  name: "Q4 2024 - יעדי מכירות",
  employee_count: 85,
  success_rate: 78,
  price_tier: 1000,
  status: "active",
  sent_count: 85,
  opened_count: 71,
  selected_count: 52,
  budget_expected: 85000,
  budget_actual: 52000,
  deadline_days: 14
};

export const MOCK_ORDERS = [
  { id: "o1", employee_name: "רון לוי", employee_email: "ron@company.co.il", product_title: "אוזניות Sony WH-1000XM5", price_tier: 1000, consumer_price: 1290, status: "delivered", selected_at: "2024-01-10T09:00:00Z" },
  { id: "o2", employee_name: "שירה כהן", employee_email: "shira@company.co.il", product_title: "לילה זוגי מלון קדם", price_tier: 1000, consumer_price: 1000, status: "shipped", selected_at: "2024-01-11T14:00:00Z" },
  { id: "o3", employee_name: "אמיר דוד", employee_email: "amir@company.co.il", product_title: 'טלוויזיה Samsung 70" QLED 4K', price_tier: 2500, consumer_price: 3199, status: "ordered", selected_at: "2024-01-12T10:00:00Z" },
  { id: "o4", employee_name: "מיכל גרין", employee_email: "michal@company.co.il", product_title: "גריל גז 3 מבערים עם כירת צד 42BTU", price_tier: 1000, consumer_price: 1690, status: "pending", selected_at: "2024-01-13T16:00:00Z" },
  { id: "o5", employee_name: "יוסי אברהם", employee_email: "yossi@company.co.il", product_title: 'טאבון גז 500° עם אבן שמוט', price_tier: 1000, consumer_price: 2490, status: "delivered", selected_at: "2024-01-09T08:00:00Z" },
];

export const STATUS_LABELS = {
  pending: "ממתין",
  selected: "נבחר",
  ordered: "הוזמן",
  shipped: "בדרך",
  delivered: "נמסר",
};

export const STATUS_COLORS = {
  pending: "bg-amber-100 text-amber-700",
  selected: "bg-blue-100 text-blue-700",
  ordered: "bg-indigo-100 text-indigo-700",
  shipped: "bg-purple-100 text-purple-700",
  delivered: "bg-green-100 text-green-700",
};